<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/01/28 13:46:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
