<?php

/**
 * JobeetCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetCategoryTable extends Doctrine_Table
{
	
	public function findOneBySlug($slug)
{
  $q = $this->createQuery('a')
    ->leftJoin('a.Translation t')
    ->andWhere('t.lang = ?', 'en')
    ->andWhere('t.slug = ?', $slug);
  return $q->fetchOne();
}
	public function getWithJobs()
	{
	$q = $this->createQuery('c')
	->leftJoin('c.JobeetJobs j')
	->where('j.expires_at > ?', date('Y-m-d H:i:s', time()));
	 $q->andWhere('j.is_activated = ?', 1);

	return $q->execute();
	}

    /**
     * Returns an instance of this class.
     *
     * @return object JobeetCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetCategory');
    }
}