<?php

/**
 * JobeetAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetAffiliateTable extends Doctrine_Table
{
  public function countToBeActivated()
  {
    $q = $this->createQuery('a')
      ->where('a.is_active = ?', 0);
 
    return $q->count();
  }

    /**
     * Returns an instance of this class.
     *
     * @return object JobeetAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetAffiliate');
    }
}