# apps/frontend/config/routing.yml
# default rules
# apps/frontend/config/routing.yml

change_language:
  url:   /change_language
  param: { module: language, action: changeLanguage }

localized_homepage:
  url:   /:sf_culture/
  param: { module: job, action: index }
  requirements:
    sf_culture: (?:fr|en)

job_search:
  url:   /:sf_culture/search
  param: { module: job, action: search }
  requirements:
    sf_culture: (?:fr|en)
    
affiliate:
  class:   sfDoctrineRouteCollection
  options:
    model: JobeetAffiliate
    actions: [new, create]
    object_actions: { wait: get }
    prefix_path:    /:sf_culture/affiliate
  requirements:
    sf_culture: (?:fr|en) 
    
api_jobs:
  url:     /api/:token/jobs.:sf_format
  class:   sfDoctrineRoute
  param:   { module: api, action: list }
  options: { model: JobeetJob, type: list, method: getForToken }
  requirements:
    sf_format: (?:xml|json|yaml)
    
category:
  url:     /:sf_culture/category/:slug.:sf_format
  class:   sfDoctrineRoute
  param:   { module: category, action: show, sf_format: html }
  options: { model: JobeetCategory, type: object }
  requirements:
    sf_format: (?:html|atom)
    sf_culture: (?:fr|en)
    
job:
  class:   sfDoctrineRouteCollection
  options:
    model:          JobeetJob
    column:         token
    object_actions: { publish: put }
    prefix_path:    /:sf_culture/job
  requirements:
    token: \w+

job_show_user:
 url: /:sf_culture/job/:company_slug/:location_slug/:id/:position_slug
 class: sfDoctrineRoute
 options:
  model: JobeetJob
  type: object
  method_for_query: retrieveActiveJob
 param: { module: job, action: show }
 requirements:
  id: \d+
  sf_method: [GET]

homepage:
 url: /
 param: { module: job, action: index }

default_index:
 url: /:module
 param: { action: index }
 default:
 url: /:module/:action/*

